//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPTimeTableIT.Models
{
    using CAPTimeTableIT.Domain;
    using System;
    using System.Collections.Generic;
    
    public class Class : BaseEntity
    {
        public string MaGocLHP { get; set; }
        public string MaLHP { get; set; }
        public int? SoTC { get; set; }
        public string LoaiHP { get; set; }
        public string MaLop { get; set; }
        public int? TMSH { get; set; }
        public int? SoTietDaXep { get; set; }
        public string PH { get; set; }
        public string Thu { get; set; }
        public int? TietBD { get; set; }
        public int? SoTiet { get; set; }
        public string TietHoc { get; set; }
        public string Phong { get; set; }
        public string PH_X { get; set; }
        public int? SucChua { get; set; }
        public int? SiSoTKB { get; set; }
        public int? Trong { get; set; }
        public string TinhTrangLHP { get; set; }
        public string TuanHoc2 { get; set; }
        public int? ThuS { get; set; }
        public int? TietS { get; set; }
        public int? SoSVDK { get; set; }
        public int? TuanBD { get; set; }
        public int? TuanKT { get; set; }
        public string MaNganh { get; set; }
        public string TenNganh { get; set; }
        public string Note { get; set; }

        public int? SubjectId { get; set; }
        public int? SemesterId { get; set; }

        public string TeacherId { get; set; }
        public string TeacherEmail { get; set; }
        public string CreatedAssignerId { get; set; }
        public string LastModifiedAssignerId { get; set; }

        public virtual Semester Semester { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual TimeTable TimeTables { get; set; }

    }
}
